datamodule:
  # must use the absolute path of dataset to work with hydra
  zarr_path: ~/dev/garmentnets/data/garmentnets_dataset.zarr/Dress
  metadata_cache_dir: ~/local/.cache/metadata_cache_dir
  batch_size: 24
  num_workers: 4
  # sample size
  num_pc_sample: 6000
  num_volume_sample: 6000
  num_surface_sample: 6000
  num_mc_surface_sample: 0
  # mixed sampling config
  surface_sample_ratio: 0
  surface_sample_std: 0.05
  # surface sample noise
  # use 0.5
  surface_normal_noise_ratio: 0
  surface_normal_std: 0.01
  # data augumentation
  enable_augumentation: True
  random_rot_range: [-180,180]
  num_views: 4
  # volume
  volume_size: 128
  # or nocs_signed_distance_field or nocs_occupancy_grid or sim_nocs_winding_number_field or nocs_distance_field
  volume_group: nocs_winding_number_field
  # use 0.05
  tsdf_clip_value: null
  volume_absolute_value: False
  include_volume: False
  # random seed
  static_epoch_seed: False
  # datamodule config
  dataset_split: [8,1,1]
  split_seed: 0

pointnet2_model:
  checkpoint_path: ~/dev/garmentnets/data/garmentnets_checkpoints/pointnet2_checkpoints/Dress_pointnet2.ckpt
conv_implicit_model:
  volume_agg_params:
    nn_channels: [137,137,128]
    batch_norm: True
    lower_corner: [0,0,0]
    upper_corner: [1,1,1]
    grid_shape: [32,32,32]
    reduce_method: max
    include_point_feature: True
    include_confidence_feature: True
  unet3d_params:
    in_channels: 128
    out_channels: 128
    f_maps: 32
    layer_order: gcr
    num_groups: 8
    num_levels: 4
  volume_decoder_params:
    nn_channels: [128,256,256,1]
    batch_norm: True
  surface_decoder_params:
    nn_channels: [128,256,256,3]
    batch_norm: True
  mc_surface_decoder_params:
    nn_channels: [128,256,256,1]
    batch_norm: True
  volume_loss_weight: 1.0
  surface_loss_weight: 1.0
  mc_surface_loss_weight: 0
  volume_classification: False
  volume_task_space: False
  learning_rate: 0.0001
  loss_type: l2
  vis_per_items: 21
  max_vis_per_epoch_train: 10
  max_vis_per_epoch_val: 40
trainer:
  gpus: [0]
logger:
  offline: True
  name: null
  tags: []
logger_watch:
  log: gradients
  log_freq: 100
